// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABRDcgjT6k1db0b7P7Wl1d5RakoL6dFIs',
    appId: '1:352405451285:web:67f9816213253a3da7141c',
    messagingSenderId: '352405451285',
    projectId: 'quest-picker',
    authDomain: 'quest-picker.firebaseapp.com',
    databaseURL: 'https://quest-picker-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quest-picker.appspot.com',
    measurementId: 'G-2FM1Q4SZKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACNW-fPmwltmJXxFNHyr5wwIiO-73fJHY',
    appId: '1:352405451285:android:9c56d5e0aa7e4b1ba7141c',
    messagingSenderId: '352405451285',
    projectId: 'quest-picker',
    databaseURL: 'https://quest-picker-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quest-picker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmQrZbMtZnJ9PSCuvZBARMco8TM2bkimQ',
    appId: '1:352405451285:ios:ed905183cf167403a7141c',
    messagingSenderId: '352405451285',
    projectId: 'quest-picker',
    databaseURL: 'https://quest-picker-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quest-picker.appspot.com',
    iosClientId: '352405451285-2p2cac3s1rlih3942prf3st0h06b4i59.apps.googleusercontent.com',
    iosBundleId: 'com.example.questPeak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmQrZbMtZnJ9PSCuvZBARMco8TM2bkimQ',
    appId: '1:352405451285:ios:ed905183cf167403a7141c',
    messagingSenderId: '352405451285',
    projectId: 'quest-picker',
    databaseURL: 'https://quest-picker-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quest-picker.appspot.com',
    iosClientId: '352405451285-2p2cac3s1rlih3942prf3st0h06b4i59.apps.googleusercontent.com',
    iosBundleId: 'com.example.questPeak',
  );
}
