name: Flutter test app and build android apk

on:
  push:
    branches:
      - main
    tags:
      - v1.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v1
        with:
         java-version: "12.x"
      
      # Set up flutter environment      
      - uses: subosito/flutter-action@v1
        with:
         channel: "stable"


      - run: flutter pub get

      - run: flutter format
      
      - name: Flutter lint (analyze)
        run: sh ./analyze.sh
      
      - run: flutter test
